In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 创建0维张量
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
# 创建1维张量
tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
# 创建二维张量
tf.constant([[1,2],
             [3,4],
             [5,6]],
            dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [6]:
# 创建三维张量
tf.constant([
    [[1,2,3,4,5],
     [2,3,4,5,6]],
    [[1,2,3,4,5],
     [2,3,4,5,6]]
],dtype=tf.float64)

<tf.Tensor: shape=(2, 2, 5), dtype=float64, numpy=
array([[[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]],

       [[1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]]])>